<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();?>

<?
$APPLICATION->IncludeComponent(
	"bitrix:socialnetwork.user_search",
	"",
	Array(
		"SET_TITLE" => "Y",
		"USER_VAR" => $arResult["ALIASES"]["user_id"],
		"PAGE_VAR" => $arResult["ALIASES"]["page"],
		"PATH_TO_USER" => $arResult["PATH_TO_USER"],
		"PATH_TO_SEARCH" => $arResult["PATH_TO_SEARCH"],
		"PATH_TO_SEARCH_INNER" => $arResult["PATH_TO_SEARCH_INNER"],
		"ITEMS_COUNT" => $arParams["ITEM_DETAIL_COUNT"],
		"DATE_TIME_FORMAT" => $arResult["DATE_TIME_FORMAT"],
		"USER_FIELDS_SEARCH_SIMPLE" => $arResult["USER_FIELDS_SEARCH_SIMPLE"],
		"USER_FIELDS_SEARCH_ADV" => $arResult["USER_FIELDS_SEARCH_ADV"],
		"USER_PROPERTIES_SEARCH_SIMPLE" => $arResult["USER_PROPERTIES_SEARCH_SIMPLE"],
		"USER_PROPERTIES_SEARCH_ADV" => $arResult["USER_PROPERTIES_SEARCH_ADV"],
		"SONET_USER_FIELDS_LIST" => $arResult["SONET_USER_FIELDS_LIST"],
		"SONET_USER_PROPERTY_LIST" => $arResult["SONET_USER_PROPERTY_LIST"],
		"SONET_USER_FIELDS_SEARCHABLE" => $arResult["SONET_USER_FIELDS_SEARCHABLE"],
		"SONET_USER_PROPERTY_SEARCHABLE" => $arResult["SONET_USER_PROPERTY_SEARCHABLE"],
		"SHOW_YEAR" => $arParams["SHOW_YEAR"],
		"PATH_TO_USER_FRIENDS_ADD" => $arResult["PATH_TO_USER_FRIENDS_ADD"],
		"PATH_TO_MESSAGE_FORM" => $arResult["PATH_TO_MESSAGE_FORM"],
		"PATH_TO_MESSAGES_CHAT" => $arResult["PATH_TO_MESSAGES_CHAT"],
	),
	$component
);
?>
