<?
$arUrlRewrite = array(
	array(
		"CONDITION" => "#^/devsearch/([^\\.]+)/page/([0-9]+)/#",
		"RULE" => "s=\$1&PAGER_1=\$2",
		"ID" => "",
		"PATH" => "/recipe/public/dev_search.php",
	),
	array(
		"CONDITION" => "#^/ingredient/([a-zA-Z_\\-]+)/(.*)#",
		"RULE" => "CODE=\$1",
		"ID" => "",
		"PATH" => "/ingredient/index.php",
	),
	array(
		"CONDITION" => "#^/search/([^\\.]+)/page/([0-9]+)/#",
		"RULE" => "s=\$1&PAGER_1=\$2",
		"ID" => "",
		"PATH" => "/recipe/public/search.php",
	),
	array(
		"CONDITION" => "#^/profile/([0-9]+)/foodshots/#",
		"RULE" => "u=\$1",
		"ID" => "",
		"PATH" => "/personal/foodshots.php",
	),
	array(
		"CONDITION" => "#^/profile/([0-9]+)/favorites/#",
		"RULE" => "u=\$1",
		"ID" => "",
		"PATH" => "/personal/favorites.php",
	),
	array(
		"CONDITION" => "#^/profile/([0-9]+)/opinions/#",
		"RULE" => "u=\$1",
		"ID" => "",
		"PATH" => "/personal/opinion.php",
	),
	array(
		"CONDITION" => "#^/detail/([a-zA-Z_\\-]+)/(.)*#",
		"RULE" => "c=\$1",
		"ID" => "",
		"PATH" => "/recipe/public/detail.php",
	),
	array(
		"CONDITION" => "#^/profile/([0-9]+)/comments/#",
		"RULE" => "u=\$1",
		"ID" => "",
		"PATH" => "/personal/comments.php",
	),
	array(
		"CONDITION" => "#^/profile/([0-9]+)/kitchen/#",
		"RULE" => "u=\$1",
		"ID" => "",
		"PATH" => "/personal/kitchen.php",
	),
	array(
		"CONDITION" => "#^/profile/([0-9]+)/recipes/#",
		"RULE" => "u=\$1",
		"ID" => "",
		"PATH" => "/personal/recipes.php",
	),
	array(
		"CONDITION" => "#^/profile/([0-9]+)/topics/#",
		"RULE" => "u=\$1",
		"ID" => "",
		"PATH" => "/personal/topics.php",
	),
	array(
		"CONDITION" => "#^/profile/([0-9]+)/badges/#",
		"RULE" => "u=\$1",
		"ID" => "",
		"PATH" => "/personal/badges.php",
	),
	array(
		"CONDITION" => "#^/fr/recipe/edit/([0-9]+)/#",
		"RULE" => "r=\$1",
		"ID" => "",
		"PATH" => "/fr/recipe/edit.php",
	),
	array(
		"CONDITION" => "#^/ingredient/([0-9]+)/(.*)#",
		"RULE" => "ID=\$1",
		"ID" => "",
		"PATH" => "/ingredient/index.php",
	),
	array(
		"CONDITION" => "#^/recipe/delete/([0-9]+)/#",
		"RULE" => "r=\$1",
		"ID" => "",
		"PATH" => "/recipe/public/delete.php",
	),
	array(
		"CONDITION" => "#^/profile/([0-9]+)/lenta/#",
		"RULE" => "u=\$1",
		"ID" => "",
		"PATH" => "/personal/lenta.php",
	),
	array(
		"CONDITION" => "#^/recipe/edit/([0-9]+)/#",
		"RULE" => "r=\$1",
		"ID" => "",
		"PATH" => "/recipe/public/edit.php",
	),
	array(
		"CONDITION" => "#^/fr/recipe/edit/post/#",
		"RULE" => "",
		"ID" => "",
		"PATH" => "/fr/recipe/edit.post.php",
	),
	array(
		"CONDITION" => "#^/devsearch/([^\\.]+)/#",
		"RULE" => "s=\$1",
		"ID" => "",
		"PATH" => "/recipe/public/dev_search.php",
	),
	array(
		"CONDITION" => "#^/profile/favorites/#",
		"RULE" => "place=pr_favor",
		"ID" => "",
		"PATH" => "/personal/favorites.php",
	),
	array(
		"CONDITION" => "#^/profile/foodshots/#",
		"RULE" => "",
		"ID" => "",
		"PATH" => "/personal/foodshots.php",
	),
	array(
		"CONDITION" => "#^/foodshot/([0-9]+)/#",
		"RULE" => "id=\$1",
		"ID" => "",
		"PATH" => "/foodshot/index.php",
	),
	array(
		"CONDITION" => "#^/profile/edit/post/#",
		"RULE" => "",
		"ID" => "",
		"PATH" => "/personal/edit.post.php",
	),
	array(
		"CONDITION" => "#^/devdetail/([0-9]+)#",
		"RULE" => "r=\$1",
		"ID" => "",
		"PATH" => "/recipe/admin/detail.php",
	),
	array(
		"CONDITION" => "#^/all/page/([0-9]+)/#",
		"RULE" => "PAGEN_1=\$1",
		"ID" => "",
		"PATH" => "/recipe/public/list.php",
	),
	array(
		"CONDITION" => "#^/fr/detail/([0-9]+)#",
		"RULE" => "r=\$1",
		"ID" => "",
		"PATH" => "/fr/recipe/detail.php",
	),
	array(
		"CONDITION" => "#^/profile/subscribe/#",
		"RULE" => "place=pr_subscribe",
		"ID" => "",
		"PATH" => "/personal/subscription.php",
	),
	array(
		"CONDITION" => "#^/profile/comments/#",
		"RULE" => "place=pr_comment",
		"ID" => "",
		"PATH" => "/personal/comments.php",
	),
	array(
		"CONDITION" => "#^/recipe/edit/post/#",
		"RULE" => "",
		"ID" => "",
		"PATH" => "/recipe/public/edit.post.php",
	),
	array(
		"CONDITION" => "#^/profile/opinions/#",
		"RULE" => "place=pr_opinion",
		"ID" => "",
		"PATH" => "/personal/opinion.php",
	),
	array(
		"CONDITION" => "#^/profile/([0-9]+)#",
		"RULE" => "u=\$1",
		"ID" => "",
		"PATH" => "/personal/detail.php",
	),
	array(
		"CONDITION" => "#^/search/([^\\.]+)/#",
		"RULE" => "s=\$1",
		"ID" => "",
		"PATH" => "/recipe/public/search.php",
	),
	array(
		"CONDITION" => "#^/recipe/add/post/#",
		"RULE" => "",
		"ID" => "",
		"PATH" => "/recipe/public/add.post.php",
	),
	array(
		"CONDITION" => "#^/profile/kitchen/#",
		"RULE" => "",
		"ID" => "",
		"PATH" => "/personal/kitchen.php",
	),
	array(
		"CONDITION" => "#^/profile/recipes/#",
		"RULE" => "place=pr_recipe",
		"ID" => "",
		"PATH" => "/personal/recipes.php",
	),
	array(
		"CONDITION" => "#^/detail/([0-9]+)#",
		"RULE" => "r=\$1",
		"ID" => "",
		"PATH" => "/recipe/public/detail.php",
	),
	array(
		"CONDITION" => "#^/profile/topics/#",
		"RULE" => "place=pr_topic",
		"ID" => "",
		"PATH" => "/personal/topics.php",
	),
	array(
		"CONDITION" => "#^/profile/badges/#",
		"RULE" => "",
		"ID" => "",
		"PATH" => "/personal/badges.php",
	),
	array(
		"CONDITION" => "#^/recipe/([0-9]+)#",
		"RULE" => "r=\$1",
		"ID" => "",
		"PATH" => "/recipe/public/detail.php",
	),
	array(
		"CONDITION" => "#^/profile/lenta/#",
		"RULE" => "place=pr_lenta",
		"ID" => "",
		"PATH" => "/personal/lenta.php",
	),
	array(
		"CONDITION" => "#^/admin/recipe/#",
		"RULE" => "",
		"ID" => "",
		"PATH" => "/recipe/admin/list.php",
	),
	array(
		"CONDITION" => "#^/registration/#",
		"RULE" => "",
		"ID" => "bitrix:main.register",
		"PATH" => "/registration/index.php",
	),
	array(
		"CONDITION" => "#^/foodshot/add/#",
		"RULE" => "",
		"ID" => "",
		"PATH" => "/foodshot/index.php",
	),
	array(
		"CONDITION" => "#^/profile/edit/#",
		"RULE" => "place=pr_edit",
		"ID" => "",
		"PATH" => "/personal/edit.php",
	),
	array(
		"CONDITION" => "#^/recipes/rss/#",
		"RULE" => "",
		"ID" => "",
		"PATH" => "/recipe/public/all.rss.php",
	),
	array(
		"CONDITION" => "#^/recipe/add/#",
		"RULE" => "",
		"ID" => "",
		"PATH" => "/recipe/public/add.php",
	),
	array(
		"CONDITION" => "#^/profile/#",
		"RULE" => "place=pr_show",
		"ID" => "",
		"PATH" => "/personal/detail.php",
	),
	array(
		"CONDITION" => "#^/recipes/#",
		"RULE" => "",
		"ID" => "",
		"PATH" => "/recipe/public/list.php",
	),
	array(
		"CONDITION" => "#^/fr/all/#",
		"RULE" => "",
		"ID" => "",
		"PATH" => "/fr/recipe/list.php",
	),
	array(
		"CONDITION" => "#^/blogs/#",
		"RULE" => "",
		"ID" => "bitrix:socialnetwork",
		"PATH" => "/blogs/index.php",
	),
	array(
		"CONDITION" => "#^/all/#",
		"RULE" => "",
		"ID" => "",
		"PATH" => "/recipe/public/list.php",
	),
);

?>